### ISSUE TITLE
Echobot sample returns an error

### ISSUE THREAD

**Issue by sbawaskar** [infracloudio/msbotbuilder-go#38]
Echobot sample when called with bot framework emulator returns below error from line#30.

Line: https://github.com/infracloudio/msbotbuilder-go/blob/012518921524fa6e78dceaf6fa7d44cfcdf32e0d/samples/echobot/main.go#L30

Error:
```Failed to parse request. Authentication failed.: Could not find public key```

**Comment by sanketsudake** [comment]
@coupa-sbawaskar Are you still facing this issue?

**Comment by sbawaskar** [comment]
Not getting this error now. Closing this issue.

**Comment by arthurvaverko-kaltura** [comment]
im getting this issue now :\
emulator version 4 
what public key is he referring to ?
