### ISSUE TITLE
Breaking change in latest github.com/lestrrat-go/jwx

### ISSUE THREAD

**Issue by tbarnes94** [infracloudio/msbotbuilder-go#41]
New users may invoke `go get -u github.com/infracloudio/msbotbuilder-go` like the README says and receive the latest version of github.com/lestrrat-go/jwx.

For stability, keep go.mod version of github.com/lestrrat-go/jwx at v0.9.0.

See release notes: https://github.com/lestrrat-go/jwx/releases/tag/v1.0.0

> `jwk.Materialize` has been renamed to `Raw()`. A new corresponding
      method to initialize the key from a raw key (RSA/ECDSA/byte keys)
      called `FromRaw()` has also been added, which makes a nice pair.

**Comment by PrasadG193** [comment]
@tbarnes94 We do set github.com/lestrrat-go/jwx version to v0.9.0 in go.mod. 
https://github.com/infracloudio/msbotbuilder-go/blob/develop/go.mod#L7

**Comment by mattetti** [comment]
I'm not sure it's related but I tried to pull the latest version as per the doc and something related the jwk didn't go well.

```
go get -u github.com/infracloudio/msbotbuilder-go/...
go: downloading github.com/infracloudio/msbotbuilder-go v0.2.0
go: found github.com/infracloudio/msbotbuilder-go/... in github.com/infracloudio/msbotbuilder-go v0.2.0
go: downloading github.com/lestrrat-go/jwx v0.9.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/pkg/errors v0.9.0
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/lestrrat-go/jwx upgrade => v1.0.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/lestrrat-go/jwx v1.0.2
go: downloading github.com/lestrrat-go/iter v0.0.0-20200422075355-fc1769541911
# github.com/infracloudio/msbotbuilder-go/connector/auth
../../golang/pkg/mod/github.com/infracloudio/msbotbuilder-go@v0.2.0/connector/auth/jwt_token_validation.go:111:4: not enough arguments to return
../../golang/pkg/mod/github.com/infracloudio/msbotbuilder-go@v0.2.0/connector/auth/jwt_token_validation.go:111:17: key[0].Materialize undefined (type jwk.Key has no field or method Materialize)
```

**Comment by mattetti** [comment]
FYI I had to change my own go.mod to point to version 0.9.0 mentioned above:

```
github.com/lestrrat-go/jwx v0.9.0
```

**Comment by ItalyPaleAle** [comment]
This was fixed with https://github.com/infracloudio/msbotbuilder-go/commit/9c85b4dbf3e4e7d3a71dd7bf65d17d49869a424b

**Comment by PrasadG193** [comment]
Thanks, @ItalyPaleAle for confirming. Closing this.
