### ISSUE TITLE
Hello everyone, please how do I get the user's email?

### ISSUE THREAD

**Issue by faelp22** [infracloudio/msbotbuilder-go#71]
I'm migrating from the Java SDK to Go and one of the features I need is "getMember". I haven't found it or I don't know if it's implemented here.

In the Java SDK I do it this way
`CompletableFuture<TeamsChannelAccount> member = TeamsInfo.getMember(turnContext, turnContext.getActivity().getFrom().getId());
				if (member.get().getAadObjectId() != null) {
					profile.setName(member.get().getGivenName());
					profile.setEmail(member.get().getEmail().toLowerCase());
				}`

I would like to know if it is possible to get the user's email using this package and if not, I would like to implement this functionality.

If it is to be implemented, I would like to know if this information already comes in the request or if I will need to consume an API to fetch it.

I thank the attention.

**Comment by pkosiec** [comment]
Hey @faelp22, this will be possible after merging PR #74. Once you have team ID + member ID, you'll be able to use this new `Get` method 👍

**Comment by faelp22** [comment]
Thank you very much, this will be very useful in my activities and I believe it will help other people too!
